-- Auto-Translating Manga Website
-- Full PostgreSQL bootstrap schema
-- Usage (psql):
--   psql -U postgres -f src/backend/sql/init_schema.sql

CREATE DATABASE manga_website;

\connect manga_website;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =========================
-- Core dictionary tables
-- =========================

CREATE TABLE IF NOT EXISTS role (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(100),
  role_code VARCHAR(20) UNIQUE,
  role_description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS languages (
  language_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_name TEXT NOT NULL,
  language_code VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS authors (
  author_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author_name VARCHAR(255) NOT NULL,
  biography TEXT,
  avatar_url TEXT
);

-- =========================
-- Users & auth
-- =========================

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password TEXT,
  phone VARCHAR(50),
  address TEXT,
  avatar TEXT,
  role_id INTEGER NOT NULL,
  coin_balance INTEGER NOT NULL DEFAULT 0,
  user_status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT users_role_fk FOREIGN KEY (role_id) REFERENCES role(role_id),
  CONSTRAINT users_status_check CHECK (user_status IN ('active', 'ban'))
);

CREATE TABLE IF NOT EXISTS user_providers (
  user_id INTEGER NOT NULL,
  provider VARCHAR(50) NOT NULL,
  provider_id VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, provider),
  CONSTRAINT user_providers_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS otp_codes (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp VARCHAR(20) NOT NULL,
  otp_expiry TIMESTAMP DEFAULT (NOW() + INTERVAL '2 minutes'),
  created_at TIMESTAMP DEFAULT NOW()
);

-- =========================
-- Manga domain
-- =========================

CREATE TABLE IF NOT EXISTS mangas (
  manga_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  cover_image TEXT,
  status VARCHAR(30) DEFAULT 'draft',
  is_highlighted BOOLEAN DEFAULT FALSE,
  highlight_end_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  author_id INTEGER,
  uploader_id INTEGER,
  original_language TEXT,
  slug TEXT UNIQUE,
  processing_error TEXT,
  review_note TEXT,
  CONSTRAINT mangas_author_fk FOREIGN KEY (author_id) REFERENCES authors(author_id) ON DELETE SET NULL,
  CONSTRAINT mangas_uploader_fk FOREIGN KEY (uploader_id) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT mangas_status_check CHECK (
    status IN ('draft', 'processing', 'pending_review', 'published', 'rejected', 'processing_failed')
  )
);

CREATE TABLE IF NOT EXISTS chapters (
  chapter_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  manga_id INTEGER,
  uploader_id INTEGER,
  chapter_number DOUBLE PRECISION NOT NULL,
  title VARCHAR(255),
  price NUMERIC DEFAULT 0,
  status VARCHAR(30) DEFAULT 'draft',
  published_at TIMESTAMPTZ DEFAULT NOW(),
  processing_error TEXT,
  review_note TEXT,
  CONSTRAINT chapters_manga_fk FOREIGN KEY (manga_id) REFERENCES mangas(manga_id) ON DELETE CASCADE,
  CONSTRAINT chapters_uploader_fk FOREIGN KEY (uploader_id) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT chapters_status_check CHECK (
    status IN ('draft', 'processing', 'pending_review', 'published', 'rejected', 'processing_failed')
  )
);

CREATE TABLE IF NOT EXISTS pages (
  page_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chapter_id INTEGER,
  page_number INTEGER NOT NULL,
  image_url TEXT NOT NULL,
  language VARCHAR(50) NOT NULL DEFAULT 'original',
  CONSTRAINT pages_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE CASCADE,
  CONSTRAINT pages_chapter_page_uniq UNIQUE (chapter_id, page_number, language)
);

CREATE TABLE IF NOT EXISTS manga_genre (
  manga_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  PRIMARY KEY (manga_id, genre_id),
  CONSTRAINT manga_genre_manga_fk FOREIGN KEY (manga_id) REFERENCES mangas(manga_id) ON DELETE CASCADE,
  CONSTRAINT manga_genre_genre_fk FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL,
  manga_id INTEGER NOT NULL,
  added_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, manga_id),
  CONSTRAINT favorites_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT favorites_manga_fk FOREIGN KEY (manga_id) REFERENCES mangas(manga_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  comment_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  chapter_id INTEGER,
  content TEXT,
  rating INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT comments_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT comments_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE CASCADE,
  CONSTRAINT comments_rating_check CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS reading_history (
  user_id INTEGER NOT NULL,
  chapter_id INTEGER NOT NULL,
  manga_id INTEGER,
  last_page_read INTEGER DEFAULT 1,
  last_read_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, chapter_id),
  CONSTRAINT reading_history_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT reading_history_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE CASCADE,
  CONSTRAINT reading_history_manga_fk FOREIGN KEY (manga_id) REFERENCES mangas(manga_id) ON DELETE CASCADE
);

-- =========================
-- Payments & coin system
-- =========================

CREATE TABLE IF NOT EXISTS coin_packages (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  coins INTEGER NOT NULL,
  price NUMERIC NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT coin_packages_coins_price_uniq UNIQUE (coins, price)
);

CREATE TABLE IF NOT EXISTS deposit_transactions (
  deposit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id INTEGER,
  coin_package_id INTEGER,
  payment_method VARCHAR(100) NOT NULL,
  status VARCHAR(30) DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  order_code VARCHAR(120) UNIQUE,
  CONSTRAINT deposit_transactions_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT deposit_transactions_package_fk FOREIGN KEY (coin_package_id) REFERENCES coin_packages(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS coin_history (
  history_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  amount INTEGER NOT NULL,
  description VARCHAR(255),
  type VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT coin_history_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS purchased_chapters (
  purchase_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  chapter_id INTEGER,
  price_at_purchase INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT purchased_chapters_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
  CONSTRAINT purchased_chapters_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE SET NULL,
  CONSTRAINT purchased_chapters_user_chapter_uniq UNIQUE (user_id, chapter_id)
);

-- =========================
-- Uploader workflow
-- =========================

CREATE TABLE IF NOT EXISTS uploader_requests (
  request_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  reason TEXT NOT NULL,
  request_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  admin_note TEXT,
  request_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uploader_requests_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- =========================
-- Helpful indexes
-- =========================

CREATE INDEX IF NOT EXISTS mangas_status_idx ON mangas(status);
CREATE INDEX IF NOT EXISTS mangas_author_id_idx ON mangas(author_id);
CREATE INDEX IF NOT EXISTS mangas_uploader_id_idx ON mangas(uploader_id);
CREATE INDEX IF NOT EXISTS mangas_slug_idx ON mangas(slug);
CREATE INDEX IF NOT EXISTS chapters_manga_id_idx ON chapters(manga_id);
CREATE INDEX IF NOT EXISTS comments_chapter_id_idx ON comments(chapter_id);
CREATE INDEX IF NOT EXISTS comments_user_id_idx ON comments(user_id);
CREATE INDEX IF NOT EXISTS favorites_user_id_idx ON favorites(user_id);
CREATE INDEX IF NOT EXISTS favorites_manga_id_idx ON favorites(manga_id);
CREATE INDEX IF NOT EXISTS reading_history_manga_id_idx ON reading_history(manga_id);

-- Trigram index for fuzzy manga title search
CREATE INDEX IF NOT EXISTS manga_title_trgm_idx
ON mangas
USING gin (LOWER(title) gin_trgm_ops);

-- =========================
-- Seed data
-- =========================

INSERT INTO role (role_id, role_name, role_code, role_description)
VALUES
  (0, 'Admin', 'ADM', 'Toan quyen he thong'),
  (1, 'Reader', 'RED', 'Nguoi dung doc noi dung'),
  (2, 'Uploader', 'UPL', 'Nguoi tai va quan ly truyen')
ON CONFLICT (role_code) DO NOTHING;

INSERT INTO coin_packages (coins, price)
VALUES
  (7, 5000),
  (35, 25000),
  (111, 79000),
  (251, 179000),
  (391, 278000),
  (671, 479000)
ON CONFLICT (coins, price) DO NOTHING;

INSERT INTO languages (language_code, language_name)
VALUES
  ('en', 'English'),
  ('vi', 'Vietnamese'),
  ('zh', 'Chinese'),
  ('es', 'Spanish'),
  ('fr', 'French'),
  ('de', 'German'),
  ('pt', 'Portuguese'),
  ('ru', 'Russian'),
  ('ja', 'Japanese'),
  ('ko', 'Korean'),
  ('it', 'Italian'),
  ('ar', 'Arabic'),
  ('hi', 'Hindi'),
  ('bn', 'Bengali'),
  ('ur', 'Urdu'),
  ('id', 'Indonesian'),
  ('ms', 'Malay'),
  ('th', 'Thai'),
  ('tl', 'Tagalog'),
  ('tr', 'Turkish'),
  ('fa', 'Persian'),
  ('ta', 'Tamil'),
  ('nl', 'Dutch'),
  ('sv', 'Swedish'),
  ('pl', 'Polish'),
  ('uk', 'Ukrainian'),
  ('el', 'Greek'),
  ('he', 'Hebrew'),
  ('cs', 'Czech'),
  ('ro', 'Romanian'),
  ('hu', 'Hungarian'),
  ('da', 'Danish'),
  ('no', 'Norwegian'),
  ('fi', 'Finnish')
ON CONFLICT (language_code) DO NOTHING;

INSERT INTO genres (genre_id, genre_name, slug)
VALUES
  (1, 'Hanh dong', 'hanh-dong'),
  (2, 'Phieu luu', 'phieu-luu'),
  (3, 'Hai huoc', 'hai-huoc'),
  (4, 'Lang man', 'lang-man'),
  (5, 'Hoc duong', 'hoc-duong'),
  (6, 'Doi thuong', 'doi-thuong'),
  (7, 'Gia tuong', 'gia-tuong'),
  (8, 'Fantasy', 'fantasy'),
  (9, 'Isekai', 'isekai'),
  (10, 'Ma thuat', 'ma-thuat'),
  (11, 'Sieu nhien', 'sieu-nhien'),
  (12, 'Kinh di', 'kinh-di'),
  (13, 'Tam ly', 'tam-ly'),
  (14, 'Bi an', 'bi-an'),
  (15, 'Trinh tham', 'trinh-tham'),
  (16, 'Khoa hoc vien tuong', 'sci-fi'),
  (17, 'Mecha', 'mecha'),
  (18, 'The thao', 'the-thao'),
  (19, 'Am nhac', 'am-nhac'),
  (20, 'Cooking/Am thuc', 'am-thuc'),
  (21, 'Drama', 'drama'),
  (22, 'Shounen', 'shounen'),
  (23, 'Shoujo', 'shoujo'),
  (24, 'Seinen', 'seinen'),
  (25, 'Josei', 'josei'),
  (26, 'Tre em', 'tre-em'),
  (27, 'Quan su', 'quan-su'),
  (28, 'Lich su', 'lich-su'),
  (29, 'Hau tan the', 'hau-tan-the'),
  (30, 'Game', 'game'),
  (31, 'Vampire', 'vampire'),
  (32, 'Martial Arts/Vo thuat', 'vo-thuat'),
  (33, 'Ecchi', 'ecchi'),
  (34, 'Slice of Life', 'slice-of-life'),
  (35, 'Tragedy/Bi kich', 'bi-kich'),
  (36, 'Superhero/Sieu anh hung', 'sieu-anh-hung')
ON CONFLICT (slug) DO NOTHING;

-- Keep identity sequences in sync after explicit IDs
SELECT setval(
  pg_get_serial_sequence('role', 'role_id'),
  (SELECT COALESCE(MAX(role_id), 1) FROM role),
  true
);

SELECT setval(
  pg_get_serial_sequence('genres', 'genre_id'),
  (SELECT COALESCE(MAX(genre_id), 1) FROM genres),
  true
);
